# Generated by Django 5.1.1 on 2024-09-30 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uang', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peminjaman',
            old_name='jumlah_pinjaman',
            new_name='jumlah_peminjaman',
        ),
        migrations.RenameField(
            model_name='peminjaman',
            old_name='status_pinjaman',
            new_name='status_peminjaman',
        ),
    ]
