# Generated by Django 5.0.3 on 2024-10-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uang', '0004_aa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='jumlah_peminjaman',
            field=models.PositiveIntegerField(),
        ),
    ]

